kind: Secret
apiVersion: v1
metadata:
  name: che-env
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-as: env
data:
  HUGGINGFACE_API_KEY: Tm9uZQo=
  OPENAI_API_KEY: Tm9uZQo=
  WEAVIATE_API_KEY: Tm9uZQo=
  WEAVIATE_URL: Tm9uZQo=
type: Opaque

